version: 2
updates:
  # Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 5
    reviewers:
      - "michaelfuscoletti"
    labels:
      - "dependencies"
      - "javascript"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Swift dependencies
  - package-ecosystem: "swift"
    directory: "/ios"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 3
    reviewers:
      - "michaelfuscoletti"
    labels:
      - "dependencies"
      - "swift"
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 2
    reviewers:
      - "michaelfuscoletti"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"