name: AICLICompanion
options:
  bundleIdPrefix: com.aiclicompanion
  deploymentTarget:
    iOS: 17.0
  createIntermediateGroups: true
packages:
  AICLICompanionPackage:
    path: .
    type: local
targets:
  AICLICompanionApp:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - App
    dependencies:
      - package: AICLICompanionPackage
        product: AICLICompanion
    info:
      path: App/Info.plist
      properties:
        UIDeviceFamily: [1, 2]
        UISupportedInterfaceOrientations: 
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
          - UIInterfaceOrientationPortraitUpsideDown
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: false
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
          NSAllowsLocalNetworking: true
        NSLocalNetworkUsageDescription: "AICLI Companion needs access to your local network to connect to your development server."
        NSBonjourServices:
          - _aiclicode._tcp
          - _http._tcp
        UILaunchScreen:
          UIColorName: LaunchScreenBackground
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aiclicompanion.ios
        PRODUCT_NAME: AICLI Companion
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: 5.9
        TARGETED_DEVICE_FAMILY: 1,2