name: ClaudeCompanion
options:
  bundleIdPrefix: com.claudecompanion
  deploymentTarget:
    iOS: 17.0
packages:
  ClaudeCompanionPackage:
    path: .
targets:
  ClaudeCompanionApp:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - App
    dependencies:
      - package: ClaudeCompanionPackage
        product: ClaudeCompanion
    info:
      path: App/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.claudecompanion.ios
        PRODUCT_NAME: Claude Companion
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: 5.9