# SwiftLint configuration for Claude Companion macOS app

# Paths to include
included:
  - AICLICompanionHost

# Paths to exclude
excluded:
  - .build
  - .swiftpm
  - Package.swift
  - DerivedData

# Rules configuration
disabled_rules:
  - file_length
  - type_body_length
  - todo

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - fallthrough
  - first_where
  - flatmap_over_map_reduce
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - prefer_self_type_over_type_of_self
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rule configuration
line_length: 120

function_body_length: 50

cyclomatic_complexity:
  warning: 10
  error: 40
  ignores_case_statements: true

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80

type_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 60
    error: 100