name: ClaudeCompanionHost
options:
  bundleIdPrefix: com.claude.companion
  deploymentTarget:
    macOS: "14.0"
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"
targets:
  ClaudeCompanionHost:
    type: application
    platform: macOS
    sources:
      - ClaudeCompanionHost
    resources:
      - ClaudeCompanionHost/Assets.xcassets
    info:
      path: ClaudeCompanionHost/Info.plist
      properties:
        CFBundleDisplayName: Claude Companion Host
        LSUIElement: true
        LSApplicationCategoryType: public.app-category.developer-tools
        NSSupportsAutomaticTermination: false
        NSSupportsSuddenTermination: false
    entitlements:
      path: ClaudeCompanionHost/ClaudeCompanionHost.entitlements
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.claude.companion.host
      INFOPLIST_KEY_LSUIElement: true
      ENABLE_HARDENED_RUNTIME: true
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      SWIFT_VERSION: "5.0"
      MACOSX_DEPLOYMENT_TARGET: "14.0"
      CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: true
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: Network.framework
      - sdk: Security.framework
      - sdk: UserNotifications.framework