name: AICLICompanionHost
options:
  bundleIdPrefix: com.aicli.companion
  deploymentTarget:
    macOS: "14.0"
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"
targets:
  AICLICompanionHost:
    type: application
    platform: macOS
    sources:
      - AICLICompanionHost
    resources:
      - AICLICompanionHost/Assets.xcassets
    info:
      path: AICLICompanionHost/Info.plist
      properties:
        CFBundleDisplayName: AICLI Companion Host
        LSUIElement: true
        LSApplicationCategoryType: public.app-category.developer-tools
        NSSupportsAutomaticTermination: false
        NSSupportsSuddenTermination: false
    entitlements:
      path: AICLICompanionHost/AICLICompanionHost.entitlements
      properties:
        com.apple.security.get-task-allow: true
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.aicli.companion.host
      INFOPLIST_KEY_LSUIElement: true
      ENABLE_HARDENED_RUNTIME: true
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      SWIFT_VERSION: "5.0"
      MACOSX_DEPLOYMENT_TARGET: "14.0"
      CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: true
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: Network.framework
      - sdk: Security.framework
      - sdk: UserNotifications.framework
  
  AICLICompanionHostTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - AICLICompanionHostTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.aicli.companion.host.tests
      SWIFT_VERSION: "5.0"
      MACOSX_DEPLOYMENT_TARGET: "14.0"
      GENERATE_INFOPLIST_FILE: true
      CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: AICLICompanionHost