name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  # Create GitHub Release
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  # Build and Upload Server Package
  release-server:
    name: Release Server
    runs-on: ubuntu-latest
    needs: create-release
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: |
        cd server
        npm ci --production
    
    - name: Create tarball
      run: |
        cd server
        tar -czf ../claude-companion-server-${{ github.ref_name }}.tar.gz .
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ./claude-companion-server-${{ github.ref_name }}.tar.gz
        asset_name: claude-companion-server-${{ github.ref_name }}.tar.gz
        asset_content_type: application/gzip

  # Build and Upload iOS IPA
  release-ios:
    name: Release iOS
    runs-on: macos-latest
    needs: create-release
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app
    
    - name: Build iOS App
      run: |
        cd ios
        swift build -c release
    
    - name: Create archive
      run: |
        cd ios
        zip -r ../claude-companion-ios-${{ github.ref_name }}.zip .build/release/
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ./claude-companion-ios-${{ github.ref_name }}.zip
        asset_name: claude-companion-ios-${{ github.ref_name }}.zip
        asset_content_type: application/zip