name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday at 2 AM UTC

permissions:
  contents: read
  security-events: write

jobs:
  # Node.js Dependency Scanning
  nodejs-security:
    name: Node.js Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run npm audit
      run: |
        cd server
        npm audit --json > audit-report.json || true
    
    - name: Upload audit report
      uses: actions/upload-artifact@v3
      with:
        name: npm-audit-report
        path: server/audit-report.json
    
    - name: Check for critical vulnerabilities
      run: |
        cd server
        npm audit --audit-level=critical

  # SAST - Static Application Security Testing
  sast:
    name: SAST Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/secrets
          p/javascript
          p/typescript
      continue-on-error: true

  # iOS Security Scan
  ios-security:
    name: iOS Security Scan
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install MobSF
      run: |
        pip3 install mobsfscan
      continue-on-error: true
    
    - name: Run MobSF Scan
      run: |
        cd ios
        mobsfscan --json . || true
      continue-on-error: true

  # Container Scanning (if using Docker in future)
  container-scan:
    name: Container Security Scan
    runs-on: ubuntu-latest
    if: false # Enable when Docker is added
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'